//===================================================================================
// Microsoft patterns & practices
// Composite Application Guidance for Windows Presentation Foundation and Silverlight
//===================================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===================================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===================================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicMVVM.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicMVVM.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgeTextBoxAutomationId.
        /// </summary>
        internal static string AgeTextBox_Silverlight {
            get {
                return ResourceManager.GetString("AgeTextBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxAutomationId.
        /// </summary>
        internal static string CheckBox_Silverlight {
            get {
                return ResourceManager.GetString("CheckBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameTextBoxAutomationId.
        /// </summary>
        internal static string NameTextBox_Silverlight {
            get {
                return ResourceManager.GetString("NameTextBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 228 chars remaining.
        /// </summary>
        internal static string NumberOfCharRemainingOQ1_Silverlight {
            get {
                return ResourceManager.GetString("NumberOfCharRemainingOQ1_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 243 chars remaining.
        /// </summary>
        internal static string NumberOfCharRemainingOQ2_Silverlight {
            get {
                return ResourceManager.GetString("NumberOfCharRemainingOQ2_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 questions remaining.
        /// </summary>
        internal static string NumberOfQuesRemaining_Silverlight {
            get {
                return ResourceManager.GetString("NumberOfQuesRemaining_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumericQuestionAutomationId.
        /// </summary>
        internal static string NumericQuestion_Silverlight {
            get {
                return ResourceManager.GetString("NumericQuestion_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenQuestionAutomationId.
        /// </summary>
        internal static string OpenQuestions_Silverlight {
            get {
                return ResourceManager.GetString("OpenQuestions_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset_Silverlight {
            get {
                return ResourceManager.GetString("Reset_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicMVVM.
        /// </summary>
        internal static string SilverlightAppTitle {
            get {
                return ResourceManager.GetString("SilverlightAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit_Silverlight {
            get {
                return ResourceManager.GetString("Submit_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age should be between 16 and 120..
        /// </summary>
        internal static string ValidateAgeMessage_Silverlight {
            get {
                return ResourceManager.GetString("ValidateAgeMessage_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value needs to be a positive integer less than or equal to 15..
        /// </summary>
        internal static string ValidateNumQ_Silverlight {
            get {
                return ResourceManager.GetString("ValidateNumQ_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can be at most 2 answers selected.
        /// </summary>
        internal static string ValidationMulQ_Silverlight {
            get {
                return ResourceManager.GetString("ValidationMulQ_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationSummary.
        /// </summary>
        internal static string ValidationSummary_Silverlight {
            get {
                return ResourceManager.GetString("ValidationSummary_Silverlight", resourceCulture);
            }
        }
    }
}
