// ONAddinFavAdd.idl : IDL source for ONAddinFavAdd
//

// This file will be processed by the MIDL tool to
// produce the type library (ONAddinFavAdd.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

// Events
typedef [uuid(AAE363E2-3D91-4b0c-9021-EFDA0ACBD858)]
	enum OneNoteAddIn_Event {
		evtAddInNavigation        = 0, // Parameter is the newly active page id (empty if there is no active page)
		evtAddInHierarchyChange   = 1, // Parameter is the ObjectID of the hierarchy object that changed
	} OneNoteAddIn_Event;

[
	object,
	uuid(C9590FA7-2132-47fb-9A78-AF0BF19AF4E6),
	dual,
	helpstring("IOneNoteAddIn Interface"),
	pointer_default(unique)
]
interface IOneNoteAddIn : IDispatch
{
	/*
		Button was clicked.
		strActivePageID is the currently active page (note: might be empty, if there is no active page)
		pfEnabled indicates whether or not the addin button should be enabled
	*/
	HRESULT OnClick(
		[in]BSTR bstrActivePageID,
		[out, retval]VARIANT_BOOL * pfEnabled);

	/*
		Event occurred.
		strParameter depends on the event (see OneNoteAddIn_Event definition)
		pfEnabled indicates whether or not the addin button should be enabled (true = enabled)
	*/
	HRESULT OnEvent(
		[in]OneNoteAddIn_Event evt,
		[in]BSTR bstrParameter,
		[out, retval]VARIANT_BOOL * pfEnabled);
};

[
	uuid(6046DECA-2639-4E67-9A2F-C176F0FBF92C),
	version(1.0),
	helpstring("ONAddinFavAdd 1.0 Type Library")
]
library ONAddinFavAddLib
{
	importlib("stdole2.tlb");
	[
		uuid(29DEF9C0-B770-4b5a-9742-3DF67B4FA575),
		helpstring("AddinMain Class")
	]
	coclass AddinMain
	{
		[default] interface IOneNoteAddIn;
	};
};
